### ISSUE TITLE
Main route is getting from core module Home

### ISSUE THREAD

**Issue by twent** [tempestphp/tempest-app#3]
Hello, **Brent**!
Main route with leading slash is getting from core module Home, not from `app/HomeController`

Can I change this behavior?

![image](https://github.com/tempestphp/tempest-app/assets/7511983/a12cb519-2987-4d8e-b6cf-9fc0c643bc6f)

**Comment by brendt** [comment]
That's a regression! I'll look into fixing it today

**Comment by brendt** [comment]
Hi! Could you paste the output of `./tempest discovery:status` here? I just tried to reproduce it with a clean install and wasn't able to do so.
